### PR TITLE
fix: decode file name for analysis process notification

### LINKED ISSUE #2441: Analyzing progress message shows URL encoded characters in its path
Instead I would expect to see the unencoded string - in this particular case the parentheses.

analysing message

### PR DESCRIPTION
**Pull request by ishche**
## How Has This Been Tested?

#2441

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java [hunk 1]
```diff
@@ -152,7 +152,7 @@ private void notifyWorkProgressBegin(String uri) {
     WorkDoneProgressBegin workDoneProgressBegin = new WorkDoneProgressBegin();
     workDoneProgressBegin.setTitle(messageService.getMessage(
             "Communications.syntaxAnalysisInProgressTitle",
-            files.getNameFromURI(uri)));
+            files.getNameFromURI(files.decodeURI(uri))));
```
Comment (slavek-kucera) [inline server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java:155]: does it work reasonably well with `untitled:` or e4e schemas?

Comment (ishche) [reply server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java:155]: schemas are ignored

Comment (slavek-kucera) [reply server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java:155]: query string?

Comment (slavek-kucera) [reply server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java:155]: Both getNameFromURI implementations I found seem to treat the input as a path, not URI.

Comment (ishche) [reply server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java:155]: Do you think I should reimplement them too?

Comment (slavek-kucera) [reply server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java:155]: The File class seems to perform some kind of path normalization, I am honestly not sure what the impact might be in general. I don't know how much the implementations may vary - as far as I can tell it could be fine or it may throw on some weird input.

Comment (ishche) [reply server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/communications/ServerCommunications.java:155]: That we will address in separate PR.
