### PR TITLE
fix: Fix SET statement error for non table variables

### LINKED ISSUE #373: Use of SET verb should be flagged when used on a variable that isn't an index
## Description ##
If I have a variable defined like this:
01  FILLER.
   05  SUBSCR PIC 99.

And code this verb:
SET SUBSCR UP BY 1.
or 
SET SUBSCR TO 4.

These are syntax errors, but are not flagged.    ADD or MOVE must be used instead.

## Steps to reproduce ##
Code the above in any COBOL program, no statements are flagged.  

## Expected behavior ##
Statement should be flagged, SET is not valid on non-indexed items.

### PR DESCRIPTION
**Pull request by Nurkambay**
## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by ishche — APPROVED** [review]

File: server/engine/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java [hunk 1]
```diff
@@ -1077,6 +1074,30 @@ && ofNullable(ctx.dataOccursClause().get(0).dataOccursTo().UNBOUNDED())
             visitChildren(ctx));
   }
 
+  @Override
+  public List<Node> visitSetToStatement(SetToStatementContext ctx) {
+    List<Node> receivingField =
+            ctx.receivingField().stream().map(this::visit).flatMap(List::stream).collect(toList());
+
+    boolean address = ctx.receivingField().stream().flatMap(f -> f.children.stream())
```
Comment (slavek-kucera) [inline server/engine/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java]: `children` could be null on invalid input.

Comment (Nurkambay) [reply server/engine/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java]: Fixed

**Review by slavek-kucera — APPROVED** [review]
